[project]
src = "src"
dot_env = ".env"

[networks.contracts.price_feed]
deployer_script = "script/deploy_mocks.py"
abi = "mock_v3_aggegator"


[networks.anvil]
url = "http://localhost:8545"
save_to_db = true
prompt_live = false
default_account_name = "anvil0"
unsafe_password_file = "~/.moccasin/unsafe-passwords/anvil0"

[networks.sepolia]
url = "$SEPOLIA_RPC_URL"
save_to_db = false
default_account_name = "default"
explorer_uri ='https://eth-sepolia.blockscout.com/'
explorer_type = 'blockscout'


[networks.sepolia.contracts.price_feed]
address="0x694AA1769357215DE4FAC081bf1f309aDC325306"
deployer_script = "script/deploy_mocks.py"

[networks.sepoliazk]
url = "$ZKSYNC_SEPOLIA_RPC_URL"
is_zksync = true
save_to_db = false
chain_id = 300
#prompt_live = false
default_account_name = "default"
explorer_uri = 'https://explorer.sepolia.era.zksync.dev'
explorer_type = 'zksyncexplorer'

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
